# Generated by Django 3.1.2 on 2020-10-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201011_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='listenCount',
            field=models.IntegerField(default=0),
        ),
    ]
