# Generated by Django 3.1.2 on 2020-10-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_accounttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accountType',
        ),
    ]
