# Generated by Django 3.1.2 on 2020-10-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_accounttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accountType',
            field=models.CharField(choices=[('A', 'Artist'), ('C', 'Consumer'), ('S', 'SuperUser')], max_length=1),
        ),
    ]
